# Generated by Django 2.2.1 on 2019-05-24 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2001, 5, 24), verbose_name='birth date'),
        ),
    ]
