# Generated by Django 2.1.7 on 2019-04-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=40, unique=True, verbose_name='Название товара')),
                ('logotype', models.CharField(max_length=20, verbose_name='Логотип товара (тема)')),
                ('gender', models.CharField(choices=[('male', 'Мужское'), ('female', 'Женское'), ('boys', 'Детское (мальчик)'), ('girls', 'Детское (девочка)')], max_length=15, verbose_name='Пол')),
                ('color', models.CharField(max_length=15, verbose_name='Цвет')),
                ('article', models.CharField(max_length=15, unique=True, verbose_name='Артикл')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Процент скидки')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductBySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58')], max_length=3, verbose_name='Размер')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_by_size', to='products.Product')),
            ],
            options={
                'verbose_name': 'Размер товара',
                'verbose_name_plural': 'Размеры товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=40, unique=True, verbose_name='Категория продукта')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Категория активна')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_product', models.ImageField(upload_to='products', verbose_name='Фотография товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_img', to='products.Product')),
            ],
            options={
                'verbose_name': 'Фотографии товара',
                'verbose_name_plural': 'Фотографии товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.ProductCategory'),
        ),
    ]
