# Generated by Django 2.2.1 on 2019-05-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Продукт активен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужское'), ('woman', 'Женское')], max_length=15, verbose_name='Категория людей или тип товара'),
        ),
    ]
