# Generated by Django 2.2.1 on 2019-05-24 13:48

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190517_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_img',
            field=models.ImageField(default='', max_length=255, upload_to=products.models.get_upload_dir, verbose_name='Фотография товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужское'), ('female', 'Женское')], max_length=15, verbose_name='Категория людей или тип товара'),
        ),
    ]
