# Generated by Django 2.2.1 on 2019-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190524_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('man', 'Женское'), ('woman', 'Женское')], max_length=15, verbose_name='Категория людей или тип товара'),
        ),
    ]
